Drl 48 & 49   dev
csankit0108/Dr-Reddys-Laboratories-API pull request #12
Opened 2022-11-10 08:16 UTC by MahalakshmiSadhananthan

Before insert trigger on Lead object, 

DRL - 48 -> Check if the utm Source Campaign code on incoming lead record is matching with Campaign code on Campaign records. If the match exist then update the Source Campaign field on the (child) lead record with the matched Campaign record.

DRL - 49 -> Check if the utm Source code on incoming lead record is matching with the custom metadata UTM Source records with parameter Name. If the match exist then the matched record Lead Source value to be updated on the Lead record Lead Source field.

2022-11-10 08:56 UTC, pradeepchary commented on force-app/main/default/classes/DRLUtil.cls
> +public class DRLUtil{
```suggestion
public class DRL_Utils {
```

2022-11-10 08:56 UTC, pradeepchary commented on force-app/main/default/classes/DRLUtil.cls
> +/**
@MahalakshmiSadhananthan if this is an existing class, for what purpose we are using this?

2022-11-10 08:58 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +*  07-11-2022       |  mahalakshmi.sadhanantham@absyz.com	|  2.0          |    Process Before Trigger
Align the rows in tabular format. Version should be 1.1

2022-11-10 11:10 UTC, MahalakshmiSadhananthan commented on force-app/main/default/classes/DRLUtil.cls
> +/**
Hi @pradeepchary, Generic Methods are added to this existing class "DRLUtil".

2022-11-10 12:01 UTC, csankit0108 requested changes

2022-11-14 06:41 UTC, csankit0108 approved these changes

2022-11-14 06:49 UTC, merged