DRL-36-created custom metadata and changes
csankit0108/Dr-Reddys-Laboratories-API pull request #23
Opened 2022-11-14 14:48 UTC by Wafashk

created custom metadata and changes in test class and TriggerHelper

2022-11-14 17:29 UTC, csankit0108 requested changes

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                                                                      from Prospect_Lead_Status_Mapping__mdt
```suggestion
                                                                      FROM Prospect_Lead_Status_Mapping__mdt
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                                                                      where Lead_Status__c In:set_OldParentStatus]){
```suggestion
                                                                      WHERE Lead_Status__c IN :set_OldParentStatus]) {
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                                                                       map_getOldWeightage.put(objprospectLeadStatus.Lead_Status__c,objprospectLeadStatus.Weightage__c);
```suggestion
                                                                       map_getOldWeightage.put(objprospectLeadStatus.Lead_Status__c, objprospectLeadStatus.Weightage__c);
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                                                                       System.debug('old parent status' + dbloldWeightage );
Remove system debugs

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +        for(Prospect_Lead_Status_Mapping__mdt objprospectLeadStatus :[Select Lead_Status__c,
Can we combine this FOR loop with the above one

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +        for(Prospect_Lead_Status_Mapping__mdt objprospectLeadStatus :[Select Lead_Status__c,
Update the custom metadata api names correctly in the code

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +        for(Lead objparentLead : [select Id,
```suggestion
        for (Lead objLead : [SELECT Id,
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                               from Lead
```suggestion
                               FROM Lead
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                               where Id In: set_prospectId]){
```suggestion
                               WHERE Id In :set_prospectId]) {
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +            if(dblnewWeightage> dbloldWeightage  && strnewParentStatus != objparentLead.Status)
```suggestion
            if (dblnewWeightage > dbloldWeightage  && strnewParentStatus != objparentLead.Status)
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +
remove empty line

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +            }
add new line

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +            if(list_updateParentLead.size() > 0){
```suggestion
            if (!list_updateParentLead.isEmpty()) {
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                update list_updateParentLead;
Use Database.update and add errors to exception logs

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +        // Lead objLead = new DRL_TestUtility.LeadBuilder()
Remove commented lines

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +    private static void TestProspectStatus(){
```suggestion
    private static void testProspectStatus() {
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +      Lead objLead=[Select Id,
```suggestion
      Lead objLead = [SELECT Id,
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +                      From Lead
```suggestion
                      FROM Lead
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +                      Where Email='testuser5@yopmail.com'  and
```suggestion
                      WHERE Email ='testuser5@yopmail.com' AND
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +
remove empty lines

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +     system.debug('record fetched');
remove system debugs

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +        objLead.Status='Unqualified';
```suggestion
        objLead.Status = 'Unqualified';
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +        Update objLead;
```suggestion
        update objLead;        
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls
> +
remove empty lines

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +        }
add new line after every method ends

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +        public LeadBuilder setStatus (String strValue) {
```suggestion
        public LeadBuilder setStatus(String strValue) {
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +        public LeadBuilder setCountry (String strValue){
```suggestion
        public LeadBuilder setCountry(String strValue) {
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +         public LeadBuilder setReasonForDecline (String strValue){
```suggestion
         public LeadBuilder setReasonForDecline(String strValue){
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +            objLead.DRL_Prospect__c=this.idProspectId;
```suggestion
            objLead.DRL_Prospect__c = this.idProspectId;
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +            objLead.Status=this.strStatus;
```suggestion
            objLead.Status = this.strStatus;
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +            objLead.Country=this.strCountry;
```suggestion
            objLead.Country = this.strCountry;
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/DRL_TestUtility.cls
> +            objLead.Reason_for_Decline__c=this.strReasonForDecline;
```suggestion
            objLead.Reason_for_Decline__c = this.strReasonForDecline;
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/LeadTriggerHandler.cls
> +        Set<String> set_oldProspectStatus = new Set<String>();
```suggestion
        Set<String> set_OldProspectStatuses = new Set<String>();
```

2022-11-14 17:29 UTC, csankit0108 commented on force-app/main/default/classes/LeadTriggerHandler.cls
> +        Set<String> set_newLeadStatus = new Set<String>();
```suggestion
        Set<String> set_NewLeadStatuses = new Set<String>();
```

2022-11-16 14:33 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +        Map<String, DRL_ProspectLeadStatusMapping__mdt> map_StatusMappingByLeadStatus = new Map<String, DRL_ProspectLeadStatusMapping__mdt>();
break in to two lines

2022-11-16 14:39 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                ? (Integer)map_StatusMappingByLeadStatus.get(strLeadStatus)?.Weightage__c
```suggestion
                ? (Integer)map_StatusMappingByLeadStatus.get(strLeadStatus).Weightage__c
```
You already did a check that the map contains this particular key. the metadata record will the weightage

2022-11-16 14:42 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                ? (Integer)map_StatusMappingByLeadStatus.get(strProspectStatus)?.Weightage__c
```suggestion
                ? (Integer)map_StatusMappingByLeadStatus.get(strProspectStatus).Weightage__c
```

2022-11-16 14:46 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                (strProspectStatus != map_StatusMappingByLeadStatus.get(strLeadStatus)?.ProspectStatus__c)
```suggestion
                (strProspectStatus != map_StatusMappingByLeadStatus.get(strLeadStatus).ProspectStatus__c)
```

2022-11-16 14:46 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +                objProspect.Status = map_StatusMappingByLeadStatus.get(strLeadStatus)?.ProspectStatus__c;
```suggestion
                objProspect.Status = map_StatusMappingByLeadStatus.get(strLeadStatus).ProspectStatus__c;
```

2022-11-16 14:47 UTC, pradeepchary commented on force-app/main/default/classes/DRL_LeadTriggerHelper.cls
> +    public static void processAfterUpdate(List<Lead> list_Leads) {
the Prospect status update logic on the Lead status update can be pushed to Async method

2022-11-16 14:48 UTC, pradeepchary commented on force-app/main/default/classes/DRL_TestUtility.cls
> +            this.strStatus='';
```suggestion
            this.strStatus = '';
```

2022-11-16 14:48 UTC, pradeepchary commented on force-app/main/default/classes/DRL_TestUtility.cls
> +            this.strCountry='';
```suggestion
            this.strCountry = '';
```

2022-11-16 14:49 UTC, pradeepchary commented on force-app/main/default/classes/DRL_TestUtility.cls
> +         public LeadBuilder setReasonForDecline (String strValue){
```suggestion
         public LeadBuilder setReasonForDecline(String strValue) {
```

2022-11-16 14:50 UTC, pradeepchary approved these changes

2022-11-16 14:51 UTC, pradeepchary commented
Approving this PR, added a few comments, address them, and do test thoroughly the logic and then merge the PR

2022-11-18 10:30 UTC, csankit0108 approved these changes

2022-11-18 10:30 UTC, merged