Drl 7 : On Adding Contact to opportunity on the contact lookup field.
csankit0108/Dr-Reddys-Laboratories-API pull request #29
Opened 2022-11-16 14:50 UTC by deeksha-suvarna

**Changes :** 

API_Plus_New_OpportunityPage.cmp
API_Plus_New_OpportunityPageController.js
API_Plus_New_OpportunityPageHelper.js

2022-11-17 15:53 UTC, csankit0108 requested changes

2022-11-17 15:53 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +    validateTriggerSheetListAPI: function(component,event)
Is this an existing method or did you create it? The method name is not meaningful in our scenario

2022-11-17 15:53 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +        var isValid=true;
Are we using isValid anywhere, if not remove it

2022-11-17 15:53 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +        var contactId=component.get("v.contactId");
```suggestion
        var contactId = component.get("v.contactId");
```

2022-11-17 15:53 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +        var message;
I don't see 'message' variable being used anywhere. Remove it

2022-11-17 15:53 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +        if (contactId=='' || contactId==undefined )
```suggestion
        if (contactId === '' || contactId === undefined) {
```

2022-11-17 15:53 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +                    "message":'Contact can not be blank',
Message can be in custom label

2022-11-17 15:55 UTC, csankit0108 requested changes

2022-11-17 15:55 UTC, csankit0108 commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +            var response=component.find("APIOptyCreateForm").submit();
```suggestion
            var response = component.find("APIOptyCreateForm").submit();
```

2022-11-18 06:20 UTC, deeksha-suvarna commented on force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js
> +    validateTriggerSheetListAPI: function(component,event)
Created a new method for validation for API Record type.

2022-11-18 07:21 UTC, csankit0108 approved these changes

2022-11-18 07:22 UTC, merged