Convert Lead Component
csankit0108/Dr-Reddys-Laboratories-API pull request #35
Opened 2022-11-18 12:39 UTC by kishore-pedireddy-absyz

2022-11-23 08:02 UTC, csankit0108 commented on force-app/main/default/aura/DRL_LeadConvertSuccessSection/DRL_LeadConvertSuccessSectionController.js
> +        if(component.get('v.list_Opportunities')!=null&&component.get('v.list_Opportunities')!=undefined&&component.get('v.list_Opportunities').length>0){
```suggestion
        if (
            component.get('v.list_Opportunities') != null && 
            component.get('v.list_Opportunities') != undefined && 
            component.get('v.list_Opportunities').length > 0
        ) {
```

2022-11-23 08:25 UTC, kishore-pedireddy-absyz commented on force-app/main/default/aura/DRL_ConvertLeadOpportunitySection/DRL_ConvertLeadOpportunitySection.cmp
> +                                    <aura:if isTrue="{!objfield.required}">
Adding required attribute on lightning:inputfield adding red* even if {!objfield.required} value is false. we added aura:if to avoid this.

2022-11-23 08:27 UTC, kishore-pedireddy-absyz commented on force-app/main/default/aura/DRL_ConvertLeadOpportunitySection/DRL_ConvertLeadOpportunitySection.cmp
> +            <div class="opportunityFormSectionContainer">
added this to maintain form width similar to account and contact sections

2022-11-23 08:31 UTC, kishore-pedireddy-absyz commented on force-app/main/default/aura/DRL_ConvertLeadProspect/DRL_ConvertLeadProspect.cmp
> +    <aura:html tag="style">
Quick Action gives us modal by default which we are trying to override. styles added in component css file only applies to the elements in the component. here we are trying to override the modal that came by default with quick action.

2022-11-28 06:08 UTC, csankit0108 requested changes

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_ConvertLeadProspectController.cls
> +        List<Contact> list_contact = new List<Contact>();
```suggestion
        List<Contact> list_Contacts = new List<Contact>();
```

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_ConvertLeadProspectController.cls
> +        list_contact = strmail != null ? Database.query('SELECT ' + DRLUtil.getsObjectFieds('Contact') + 'FROM Contact WHERE email =:strmail') : list_contact ;
```suggestion
        list_contact = strmail != null ? Database.query('SELECT ' + DRLUtil.getsObjectFieds('Contact') + 'FROM Contact WHERE Email =:strmail') : list_Contacts ;
```

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_ConvertLeadProspectController.cls
> +        if(list_contact.size()>0){
Instead of using IF-ELSE, we can use 'return !list_Contacts.isEmpty()'.

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_ConvertLeadProspectController.cls
> +    public class ConvertLeadDataWrapper{
Add headers for each wrapper class and mention a description

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +
Remove empty lines

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +
Remove empty lines

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +
Remove empty lines

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +        Account obj_Account = [Select Id from Account where Name = 'Test Existing Account' LIMIT 1 ] ;
```suggestion
        Account objAccount = [SELECT Id FROM Account WHERE Name = 'Test Existing Account' LIMIT 1 ] ;
```

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +        Contact obj_Contact = [Select Id, Email from Contact where LastName = 'testExistingContact' LIMIT 1 ] ;
```suggestion
        Contact objContact = [SELECT Id, Email FROM Contact WHERE LastName = 'testExistingContact' LIMIT 1 ] ;
```

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +
Remove empty lines

2022-11-28 06:08 UTC, csankit0108 commented on force-app/main/default/classes/DRL_convertLeadProspectTest.cls
> +        Lead obj_leadProspect = [Select Id from Lead where LastName = 'testProspectLead' and RecordType.DeveloperName='DRL_Prospect' LIMIT 1 ];
```suggestion
        Lead objLeadProspect = [SELECT Id FROM Lead WHERE LastName = 'testProspectLead' AND RecordType.DeveloperName = 'DRL_Prospect' LIMIT 1];
```

2022-11-28 06:12 UTC, csankit0108 commented
@kishore-pedireddy-absyz @subhodeep-absyz 
1. Please make sure we are following proper spacing when using operators like =,+,== etc. (Eg: String strFieldName = '';)
2. Add TRY-CATCH for all main methods and create an exception log. Refer DRL_LeadTriggerHelper.
3. Use Database methods to perform any DMLs and process the errors and create exception logs if there are any errors. Refer the DMLs used in DRL_LeadTriggerHelper

2022-11-28 11:45 UTC, csankit0108 approved these changes

2022-11-28 11:45 UTC, merged