custom fields for DRL-13 and drl-35
csankit0108/Dr-Reddys-Laboratories-API pull request #4
Opened 2022-11-08 06:56 UTC by kishore-pedireddy-absyz

field information:
UTM Source custom text field of length 255 characters
*APi Name-DRL_UTM_Source
Description - DRL - To Track the source campaign

UTM Campaign custom text field of length 255 characters
*Api Name - DRL_UTM_Campaign
*Description - DRL - To track source campaign

Source Campaign custom lookup field to Campaign Object
*Description - DRL - Lookup to source campaign which brought the customer
*Api Name - DRL_Source_Campaign

2022-11-09 14:02 UTC, csankit0108 requested changes

2022-11-09 14:02 UTC, csankit0108 commented on manifest/package.xml
> +		<members>Lead.DRL_Source_Campaign__c</members>
```suggestion
		<members>Lead.DRL_SourceCampaign__c</members>
```

2022-11-09 14:02 UTC, csankit0108 commented on manifest/package.xml
> +		<members>Lead.DRL_UTM_Campaign__c</members>
```suggestion
		<members>Lead.DRL_UTMCampaign__c</members>
```

2022-11-09 14:02 UTC, csankit0108 commented on manifest/package.xml
> +		<members>Lead.DRL_UTM_Source__c</members>
```suggestion
		<members>Lead.DRL_UTMSource__c</members>
```

2022-11-09 14:03 UTC, csankit0108 commented
@kishore-pedireddy-absyz can you please make the change to the field Api names as suggested.

2022-11-10 05:53 UTC, csankit0108 commented
Add profile permissions as well

2022-11-10 08:44 UTC, pradeepchary commented on force-app/main/default/objects/Lead/fields/DRL_Source_Campaign__c.field-meta.xml
> +    <fullName>DRL_Source_Campaign__c</fullName>
API name is wrong
```suggestion
    <fullName>DRL_SourceCampaign__c</fullName>
```

2022-11-10 08:45 UTC, pradeepchary commented on force-app/main/default/objects/Lead/fields/DRL_Source_Campaign__c.field-meta.xml
> +    <description>DRL -  Lookup to source campaign which brought the customer</description>
```suggestion
    <description>DRL - Lookup to source campaign which influenced the customer</description>
```

2022-11-10 08:45 UTC, pradeepchary commented on force-app/main/default/objects/Lead/fields/DRL_UTM_Campaign__c.field-meta.xml
> +    <fullName>DRL_UTM_Campaign__c</fullName>
```suggestion
    <fullName>DRL_UTMCampaign__c</fullName>
```

2022-11-10 08:45 UTC, pradeepchary commented on force-app/main/default/objects/Lead/fields/DRL_UTM_Source__c.field-meta.xml
> +    <fullName>DRL_UTM_Source__c</fullName>
```suggestion
    <fullName>DRL_UTMSource__c</fullName>
```

2022-11-11 10:50 UTC, csankit0108 approved these changes

2022-11-11 10:51 UTC, merged